version: '3'
services:
  php:
    container_name: php-wordpress
    image: lnmp-php:v1.1
    ports:
      - 9001:9000
    networks:
      - wordpress
    volumes:
      - ./data/wordpress/:/data/wordpress/
  nginx:
    container_name: nginx-wordpress
    image: lnmp-nginx:v1.1
    ports:
      - 8066:80
    volumes:
      -  ./ubuntu/nginx/nginx-wordpress.conf:/etc/nginx/nginx.conf
      - ./data/wordpress/:/data/wordpress/
    depends_on:
      - php
    networks:
      - wordpress
  mysql:
    container_name: mysql-wordpress
    image: lnmp-mysql:v1.2
    ports:
      - 3311:3306
    networks:
      - wordpress
networks:
  wordpress:
